== Use Case Jouer

=== Revision History +

[cols=",,",options="header",]
|===
|Date |Author |Description of change
| | |
| | |
| | |
| | |
| | |
| | |
| | |
|===

Use Case Template. Copyright (c) 2004-2005 TechnoSolutions Corporation

(Learn more about “TopTeam for Use Cases” at
http://www.technosolutions.com[[.underline]#www.technosolutions.com#])

Permission is hereby granted, free of charge, to any person obtaining a
copy of this document and its associated documentation, to use the
document on their projects for any commercial or non-commercial purpose.
However you may not publish, distribute, sublicense, and/or sell copies
of this document.

THE DOCUMENT IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
DOCUMENT OR THE USE OR OTHER DEALINGS IN THE DOCUMENT. TECHNOSOLUTIONS
CORPORATION MAKES NO REPRESENTATIONS ABOUT THE SUITABILITY OF THIS
DOCUMENT FOR ANY PURPOSE. +
*Use Case:* Jouer

*Id*: UC- 1

*Description* Résumé d'une partie de RISK dans sa globalité.

*Level:* High Level Summary

*Primary Actor* Jeu

*Supporting Actors* Joueur

*Stakeholders and Interests*

*Pre-Conditions*

Au moins 3 joueurs sont présents.

*Post Conditions*

[.underline]#Success end condition#

Le jeu s'est déroulé correctement jusqu'à l'obtention d'un joueur gagnant selon les règles du jeu RISK.

[.underline]#Failure end condition#:

Un des joueurs ne réalise pas d'action et bloque le jeu.

[.underline]#Minimal Guarantee#

Pas de garantie.

*Trigger*

Un groupe de joueurs veut faire une partie.

=== Main Success Scenario

[arabic]
. Les joueurs mettent en place la partie (Voir UC2: Initialisation)
. Les joueurs jouent tour à tour (Voir UC3: Tour)
. On répète 2. tant qu'il y a plus d'un joueur sur les territoires.
. Le dernier joueur est le gagnant. La partie est terminée.



*Frequency:* Une seule fois

