== Use Case Echange de carte

=== Revision History +

[cols=",,",options="header",]
|===
|Date |Author |Description of change
| | |
| | |
| | |
| | |
| | |
| | |
| | |
|===

Use Case Template. Copyright (c) 2004-2005 TechnoSolutions Corporation

(Learn more about “TopTeam for Use Cases” at
http://www.technosolutions.com[[.underline]#www.technosolutions.com#])

Permission is hereby granted, free of charge, to any person obtaining a
copy of this document and its associated documentation, to use the
document on their projects for any commercial or non-commercial purpose.
However you may not publish, distribute, sublicense, and/or sell copies
of this document.

THE DOCUMENT IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
DOCUMENT OR THE USE OR OTHER DEALINGS IN THE DOCUMENT. TECHNOSOLUTIONS
CORPORATION MAKES NO REPRESENTATIONS ABOUT THE SUITABILITY OF THIS
DOCUMENT FOR ANY PURPOSE. +

*Use Case:* Echange de carte

*Id*: UC- 4

*Description* Le procédé par lequel un joueur échange des cartes contre des armées

*Level:* User Goal

*Primary Actor* Joueur

*Supporting Actors* Jeu

*Stakeholders and Interests* Pioche Défausse Carte Territoire Continent Main

*Pre-Conditions*

C'est au joueur de jouer. La partie n'est pas terminée.

*Post Conditions*

[.underline]#Success end condition#

Le joueur a pu échanger certaines de ses cartes contre des armées et les a placées sur ses territoires.

[.underline]#Failure end condition#:

Le joueur ne réalise aucune action.

[.underline]#Minimal Guarantee#

Le joueur ne peut que faire des échanges valides.

*Trigger*

Le joueur est en phase de renfort lors de son tour.

=== Main Success Scenario

[arabic]
. Le joueur peut échanger des jeux de 3 cartes de la forme: *extension 1*
.. 1 carte de chaque type: Fantassin, Cavalerie, Char
.. 3 cartes du même type
.. 2 cartes quelconques et une carte de type "Wild"
. Pour chaque jeu échangé, il gagne un nombre d'armées correspondant au nombre total de jeu de carte échangés depuis le début de la partie par tous les joueurs:
.. Premier échange: 4 armées
.. 2: 6
.. 3: 8
.. 4: 10
.. 5: 12
.. 6: 15
.. 7: 20
.. n: de 5 en 5...
. Une fois les cartes jouées, elles partent dans la défausse.


=== Extensions

{empty}1. Si le joueur a 5 cartes ou plus, il est obligé de faire un échange.

*Frequency:* Une fois par tour pour chaque Joueur. Quelques dizaines de fois par partie pour chaque Joueur.

