/*
 * This file was automatically generated by EvoSuite
 * Sat Dec 21 21:51:18 GMT 2019
 */

package com.acmol.risk;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import com.acmol.risk.GameController;
import com.acmol.risk.GameMessage;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class GameMessage_ESTest extends GameMessage_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      GameController gameController0 = mock(GameController.class, new ViolatedAssumptionAnswer());
      GameMessage gameMessage0 = new GameMessage(gameController0, "mapconfig.json");
  }
}
