/*
 * This file was automatically generated by EvoSuite
 * Sat Dec 21 21:51:39 GMT 2019
 */

package com.acmol.risk;

import org.junit.Test;
import static org.junit.Assert.*;
import com.acmol.risk.Continent;
import com.acmol.risk.ManualInitializer;
import com.acmol.risk.Player;
import java.util.ArrayList;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ManualInitializer_ESTest extends ManualInitializer_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ManualInitializer manualInitializer0 = new ManualInitializer();
      Player[] playerArray0 = new Player[6];
      manualInitializer0.initArmy((ArrayList<Continent>) null, playerArray0);
      assertEquals(6, playerArray0.length);
  }
}
