/*
 * This file was automatically generated by EvoSuite
 * Sat Dec 21 21:49:52 GMT 2019
 */

package com.acmol.risk;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.acmol.risk.Application;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Application_ESTest extends Application_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      String[] stringArray0 = new String[2];
      stringArray0[0] = "E'e{cxSBS";
      stringArray0[1] = ": -";
      // Undeclared exception!
      try { 
        Application.main(stringArray0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Failed to process import candidates for configuration class [com.acmol.risk.Application]; nested exception is org.evosuite.runtime.TooManyResourcesException: Loop has been executed more times than the allowed 10000
         //
         verifyException("org.springframework.context.annotation.ConfigurationClassParser", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Application application0 = new Application();
      String[] stringArray0 = new String[3];
      stringArray0[0] = "$i&";
      stringArray0[1] = "d";
      stringArray0[2] = "'':6r<36TL";
      // Undeclared exception!
      try { 
        Application.main(stringArray0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Failed to process import candidates for configuration class [com.acmol.risk.Application]; nested exception is org.evosuite.runtime.TooManyResourcesException: Loop has been executed more times than the allowed 10000
         //
         verifyException("org.springframework.context.annotation.ConfigurationClassParser", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      String[] stringArray0 = null;
      // Undeclared exception!
      try { 
        Application.main((String[]) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Args must not be null
         //
         verifyException("org.springframework.util.Assert", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Application application0 = new Application();
      String[] stringArray0 = new String[4];
      stringArray0[0] = "/ D;,X(8YG .u.c`1G?";
      stringArray0[1] = "com.acmol.risk.Application";
      stringArray0[2] = "spring.boot.enableautoconfiguration";
      stringArray0[3] = "nCrDe!dhgPNQ~?";
      // Undeclared exception!
      try { 
        Application.main(stringArray0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Failed to process import candidates for configuration class [com.acmol.risk.Application]; nested exception is org.evosuite.runtime.TooManyResourcesException: Loop has been executed more times than the allowed 10000
         //
         verifyException("org.springframework.context.annotation.ConfigurationClassParser", e);
      }
  }
}
