/*
 * This file was automatically generated by EvoSuite
 * Sat Dec 21 21:47:01 GMT 2019
 */

package com.acmol.risk;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.acmol.risk.Continent;
import com.acmol.risk.Territory;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Continent_ESTest extends Continent_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Continent continent0 = new Continent((String) null);
      continent0.territories.add((Territory) null);
      // Undeclared exception!
      try { 
        continent0.findTerritoryById((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.acmol.risk.Continent", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Continent continent0 = new Continent("BI'_q9B^0<lr");
      Territory territory0 = new Territory("BI'_q9B^0<lr");
      continent0.territories.add(territory0);
      Territory territory1 = continent0.findTerritoryById("BI'_q9B^0<lr");
      assertSame(territory1, territory0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Continent continent0 = new Continent("BI'_q9B^0<lr");
      Territory territory0 = new Territory("BI'_q9B^0<lr");
      continent0.territories.add(territory0);
      Territory territory1 = continent0.findTerritoryById((String) null);
      assertNull(territory1);
  }
}
